Lab3
aleksandrina-streltsova/spring-2020-scala pull request #1
Opened 2020-03-02 17:32 UTC by aleksandrina-streltsova

2020-03-12 07:57 UTC, eld0727 requested changes

2020-03-12 07:57 UTC, eld0727 commented on src/main/scala/BotStarter.scala
> +    reply(s"https://imgur.com/t/cats/${Await.result(service.link(), Duration.Inf)}").void
1) Вы должны использовать комбинаторы Future вместо await
2) Вы уверены, что урл всегда так формируется?

2020-03-12 07:57 UTC, eld0727 commented on src/main/scala/BotStarter.scala
> +  val service = new Service(backend)
Создание каких либо компонентов внутри других компонентов - это антипатерн. Нужно вынести его в конструктор и создавать в main

2020-03-12 07:57 UTC, eld0727 commented on src/main/scala/Service.scala
> +      list(index).id
Вам лучше искать link внутри images, он точно указывает на картинку или gif или ещё какой то другой формат, который можно передать в телеграмм

2020-03-24 07:37 UTC, eld0727 commented
Lab4 конечно надо было пушить в отдельную веточку, чтобы оно не перекликалось

2020-03-25 20:48 UTC, aleksandrina-streltsova commented
@eld0727, ага, поправили, вот новый pull request: [https://github.com/aleksandrina-streltsova/spring-2020-scala/pull/2](url)

2020-04-02 04:31 UTC, eld0727 approved these changes

2020-04-08 21:06 UTC, merged